# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DopIt
email: lantoniotrento@gmail.com
description: >
  Awesome site description here
logo: "/assets/images/beme-horiz-logo.png"
logox2: "/assets/images/beme-horiz-logo@2x.png"
logox3: "/assets/images/beme-horiz-logo@3x.png"
logosvg: "/assets/images/beme-horiz-logo.svg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dopit.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Antonio Trento'
bio: >
  An entusiast web geek that love make good marketing strategies, install and mantain web platforms.
author_image: "/assets/images/author.jpg"
twitter_username: lantoniotrento
github_username:  antoniotrento

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

# data for jekyll-seo-tags plugins
social:
  name: lantoniotrento
  links:
    - https://twitter.com/jorigamy
    - https://www.facebook.com/lantoniotrento
    - https://www.linkedin.com/in/antoniotrento
    - https://plus.google.com/u/0/b/114870349902392641766/105909498949786982602
    - https://github.com/jorigamy/jorigamy.github.io
    - https://keybase.io/antoniotrento

gems:
  - jekyll-paginate
  
